title: Product Sales Formulas
description: Demonstrate usage of formulas and equations useful for managing products and product sales
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
